site_name: My Notes

# Theme
theme:
  name: material
  palette: 
    - scheme: default 
      primary: indigo 
      accent: orange 
      toggle:
        icon: material/weather-night 
        name: 切换至夜间模式 
    - scheme: slate 
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
  language: zh
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/alwaysmissin/Notes
repo_name: alwaysmissin

plugins:
  - search: 
      lang:
        - en
        - ja
  - tags 
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list 
  - toc:
      permalink: true
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  # latex支持
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - mkdocs/css/no-footer.css
  - mkdocs/css/unordered-list-symbols.css